-- ============================================================
-- Migration 005: BLE Session codes table
-- ============================================================
-- Session codes are the cryptographic handshake at the heart of B-FAST.
-- Each code is generated by the receiver, broadcast via GATT,
-- read by the sender, and included in the payment intent.
-- A code can only be used ONCE and expires after 30 seconds.
-- ============================================================

CREATE TABLE session_codes (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Human-readable ID sent to the client (never exposes the raw code)
  sc_id           VARCHAR(32) UNIQUE NOT NULL,

  -- The receiver device that generated this session code
  receiver_device_id VARCHAR(36) NOT NULL REFERENCES devices(device_id) ON DELETE CASCADE,
  receiver_user_id   UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,

  -- The encrypted code value stored as hex (raw bytes never stored in plaintext)
  -- This is the AES-256-GCM encrypted form broadcast via GATT
  encrypted_code_b64 TEXT NOT NULL,

  status          session_code_status NOT NULL DEFAULT 'active',

  -- TTL enforcement
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '30 seconds'),

  -- Consumption tracking (replay attack prevention)
  consumed_at     TIMESTAMPTZ,
  consumed_by_tx_id UUID,         -- Set when a transaction uses this code

  CONSTRAINT chk_expires_after_created CHECK (expires_at > created_at)
);

CREATE INDEX idx_session_codes_sc_id ON session_codes(sc_id);
CREATE INDEX idx_session_codes_receiver_device ON session_codes(receiver_device_id);
CREATE INDEX idx_session_codes_status ON session_codes(status);

-- Partial index: only index active codes — these are the only ones
-- looked up in the hot payment path. Keeps the index tiny and fast.
CREATE INDEX idx_session_codes_active
  ON session_codes(receiver_device_id, expires_at)
  WHERE status = 'active';